name = "pangea-ai-chat"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# <https://github.com/cloudflare/next-on-pages/issues/801>
compatibility_date = "2023-12-01"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "pangea-ai-chat"
