name = "pangea-ai-chat"
compatibility_date = "2024-12-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "pangea-ai-chat"
